import { collection, getDocs } from 'firebase/firestore';
import Head from 'next/head';
import { useRouter } from 'next/router';
import { useEffect, useState } from 'react';
import Header from '../components/Header';
import Modal from '../components/Modal';
import NotFound from '../components/NotFound';
import UserPosts from '../components/UserPosts';
import UserProfile from '../components/UserProfile';
import { db } from '../firebase';
import { User } from '../types/User';

const Profile = () => {
  const router = useRouter();
  const username = router.query.username;
  const [userExists, setExist] = useState(false);
  const [user, setUser] = useState<User | null>(null);

  useEffect(() => {
    async function getUser() {
      const users = await getDocs(collection(db, 'users'));

      users.docs.forEach((userDoc) => {
        const usernameDoc = userDoc.id;

        if (usernameDoc == username) {
          setExist(true);
          userDoc.data();
          let thisUser: User = {
            username: username,
            avatar: userDoc.data().avatar,
            publications: userDoc.data().publications,
          };
          setUser(thisUser);
        }
      });
    }

    getUser();
  });

  return (
    <div className='bg-gray-50 h-screen overflow-y-scroll scrollbar-hide'>
      <Head>
        <title></title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Header />

      {userExists ? (
        <>
          <UserProfile username={user?.username!} avatar={user?.avatar!} publications={user?.publications} />
          <UserPosts username={user?.username!} />
        </>
      ) : (
        <NotFound />
      )}

      <Modal />
    </div>
  );
};

export default Profile;
